PATH_CSV = "C:\\Users\\016110631\Documents\\Cloud\\GCP\\voos_sample.csv"
SERVICE_ACCOUNT_PATH = r"C:\\Users\\016110631\Documents\\Cloud\\GCP\data-lake-gcp-03c73609b9a9.json"
PATH_ENTRADA = "gs://raw-etl-gcp/entrada/"
PATH_SAIDA = "gs://raw-etl-gcp/saida/"
NAME_ARCHIVE_ENTRADA = "voos_sample.csv"
NAME_ARCHIVE_SAIDA = "voos_atrasos"